apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-app
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: nginx
          ports:
            - name: tcp-80
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: tcp-80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme-issuer
  namespace: flask-app
  name: flask-app-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: 'flask-app.kat.den.sneply.mx'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-svc
                port:
                  number: 80
  tls:
    - hosts:
        - flask-app.kat.den.sneply.mx
      secretName: flask-app-tls
